name : Learning Github Action CI/CD

on: [push]

jobs: 
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checking Node Version
        run: npm --version

      - name: Stage 1 > Installing Dependencies - Frontend
        run: echo 'Stage 1 > Installing Dependencies - FrontendğŸ˜‹'

      - name: Stage 2 > Building Frontend
        run: echo 'Building Frontend > ğŸ˜'

      - name: Stage 3 > Pulling from github and deploying Backing
        run: echo 'Stage 3 > Pulling from github and deploying Backing ğŸ¤©'
